config/routes.rb
Rails.application.routes.draw do

  resources :airbuses do
    member do
      get "takeoff"
      get "landing"
    end
  end
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :jobs, :only => [:index]

  get 'home/index'
  root "airbuses#index"

end

app/models/airbus.rb
class Airbus < ActiveRecord::Base

  has_many :events

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :airbus

end

app/controllers/airbuses_controller.rb
class AirbusesController < ApplicationController
  before_action :set_airbus, only: [:show, :edit, :update, :destroy]

  # GET /airbuses
  # GET /airbuses.json
  def index
    @airbuses = Airbus.all
  end

  # GET /airbuses/1
  # GET /airbuses/1.json
  def show
    @events = @airbus.events
  end

  # GET /airbuses/new
  def new
    @airbus = Airbus.new
  end

  # GET /airbuses/1/edit
  def edit
  end

  # POST /airbuses
  # POST /airbuses.json
  def create
    @airbus = Airbus.new(airbus_params)

    respond_to do |format|
      if @airbus.save
        format.html { redirect_to @airbus, notice: 'Airbus was successfully created.' }
        format.json { render :show, status: :created, location: @airbus }
      else
        format.html { render :new }
        format.json { render json: @airbus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airbuses/1
  # PATCH/PUT /airbuses/1.json
  def update
    respond_to do |format|
      if @airbus.update(airbus_params)
        format.html { redirect_to @airbus, notice: 'Airbus was successfully updated.' }
        format.json { render :show, status: :ok, location: @airbus }
      else
        format.html { render :edit }
        format.json { render json: @airbus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airbuses/1
  # DELETE /airbuses/1.json
  def destroy
    @airbus.destroy
    respond_to do |format|
      format.html { redirect_to airbuses_url, notice: 'Airbus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def takeoff
    Airbus.find(params[:id]).update_column :status, 1
    job_id = AirbusWorker.perform_async(params[:id])
    Event.create(change_status: 1, airbus_id: params[:id],updated: 1)
    render json: {job_id: job_id}
  end

  def landing
    Airbus.find(params[:id]).update_column :status, 0
    Event.create(change_status: 0, airbus_id: params[:id],updated: 1)
    render json: {success: "ok"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airbus
      @airbus = Airbus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airbus_params
      params.require(:airbus).permit(:status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    event = Event.where(updated: 0).first
    if event.present?
      event.update_column :updated, 1
      render json: {data: [event.airbus_id]}
    else
      render json: {data: ""}
    end
  end

end

app/helpers/airbuses_helper.rb
module AirbusesHelper

  def get_status_air(status)
    case status
      when 0
        "<span style='color:black'>В ангаре</span>".html_safe
      when 1
        "<span style='color:#dbb520'>Одидание</span>".html_safe
      when 2
        "<span style='color:green'>В воздухе</span>".html_safe
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/airbuses/_form.html.haml
= form_for @airbus do |f|
  - if @airbus.errors.any?
    #error_explanation
      %h2= "#{pluralize(@airbus.errors.count, "error")} prohibited this airbus from being saved:"
      %ul
        - @airbus.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :status
    = f.number_field :status
  .actions
    = f.submit 'Save'

app/views/airbuses/edit.html.haml
%h1 Editing airbus

= render 'form'

= link_to 'Show', @airbus
\|
= link_to 'Back', airbuses_path

app/views/airbuses/index.html.haml
%h1 Listing airbuses

%table
  %thead
    %tr
      %th Number
      %th Status
      %th
      %th
      %th

  %tbody
    - @airbuses.each do |airbus|
      %tr
        %td= airbus.id
        %td{class: "status_#{airbus.id}"}= get_status_air(airbus.status)
        %td= link_to 'History', airbus
        %td= link_to 'Takeoff', "javascript:void(0)", data: {id: airbus.id}, class: "takeoff"
        %td= link_to 'Landing', "javascript:void(0)", data: {id: airbus.id}, class: "landing"



%br

= link_to 'New Airbus', new_airbus_path

app/views/airbuses/new.html.haml
%h1 New airbus

= render 'form'

= link_to 'Back', airbuses_path

app/views/airbuses/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @airbus.status

%table
  %thead
    %tr
      %th Time
      %th Status
      %th
      %th
      %th

  %tbody
    - @events.each do |event|
      %tr
        %td= event.created_at
        %td= get_status_air(event.change_status)


= link_to 'Edit', edit_airbus_path(@airbus)
\|
= link_to 'Back', airbuses_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SidekiqApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>